[tool.poetry]
name = "aidev2"
version = "0.1.0"
description = ""
authors = ["Jakub Rosa <jakub.rosa.95@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
requests-random-user-agent = "^2023.2.15"
langchain = "^0.1.16"
openai = "^1.23.2"
tiktoken = "^0.6.0"
pydub = "^0.25.1"
transformers = "^4.40.0"
chromadb = "^0.4.24"
sentence-transformers = "^2.7.0"
lxml = "^5.2.1"
beautifulsoup4 = "^4.12.3"
flask = "^3.0.3"
unidecode = "^1.3.8"
tqdm = "^4.66.2"
joblib = "^1.4.0"
google-search-results = "^2.4.2"
pyarrow = "^16.0.0"
pandas = "^2.2.2"
markdown = "^3.6"
langchain-openai = "^0.1.3"
faiss-cpu = "^1.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
